# Generated by Django 3.2.4 on 2021-06-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/anonymous.jpg', upload_to='profile_picture'),
        ),
    ]
